source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YakKit_Example', :exclusive => true do
  pod "YakKit", :path => "../"
end

target 'YakKit_Tests', :exclusive => true do
  pod "YakKit", :path => "../"

  
end
