source 'https://github.com/CocoaPods/Specs.git'

target 'YakKit_Example', :exclusive => true do
  pod "YakKit", :path => "../"
end

target 'YakKit_Tests', :exclusive => true do
  pod "YakKit", :path => "../"
end

